# Generated by Django 5.0.7 on 2024-08-13 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_turnos', '0002_remove_turno_fecha_hora_turno_fecha_turno_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='fecha',
            field=models.DateField(default=datetime.date(2100, 1, 1)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turno',
            name='hora',
            field=models.TimeField(),
        ),
    ]
