# Generated by Django 5.0.7 on 2024-08-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_turnos', '0005_paciente_apellido_paciente_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='media/archivos/'),
        ),
    ]
